### ISSUE TITLE
Thanks for creating clucene on git

### ISSUE THREAD

**Issue by vikasgupta-iphone** [cataliniacob/clucene#1]
Hi Catalin, 
        I am try to search full text search approach for iOS . CLucene is good regarding fuzzy/fast search but I didn't get any update clucene. It will great help if you tell i have to use Clucene or any other approach where i have to work. Thanks

**Comment by cataliniacob** [comment]
Be aware that this is just a place to save a small patch I stumbled upon. I'm not keeping this tree up to date. I also can't advice you whether to use CLucene or not, sorry (no iOS experience and almost no CLucene experience).
